export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const FETCH_CALENDARS = "FETCH_CALENDARS";
export const FETCH_CALENDAR = "FETCH_CALENDAR";
export const CREATE_CALENDAR = "CREATE_CALENDAR";
export const EDIT_CALENDAR = "EDIT_CALENDAR";
export const DELETE_CALENDAR = "DELETE_CALENDAR";

export const SELECT_ATUAL_CALENDAR = "SELECT_ATUAL_CALENDAR";
export const EDIT_ATUAL_CALENDAR = "EDIT_ATUAL_CALENDAR";
export const DESSELECT_ATUAL_CALENDAR = "DESELECT_ATUAL_CALENDAR";
